title: Fiasco Playsets
email: verhoevenv@gmail.com
description: >
  A listing of Fiasco playsets
baseurl: ""
url: "http://verhoevenv.github.io/fiasco-playsets"

markdown: kramdown

exclude:
  - "README.md"
  - "LICENSE"
